services:

  bdd_mysql:
    image: mysql:debian
    container_name: bdd_mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - bdd_mysql_data:/var/lib/mysql
    networks: 
      - lnmp_network

  app_php:
    build:
      context: .
      dockerfile: php-dockerfile
    image: php-fpm-alpine
    container_name: app_php
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./workdir:/var/www/html
    depends_on:
      - bdd_mysql
    networks: 
      - lnmp_network
    working_dir: /var/www/html

  server_nginx:
    image: nginx:alpine
    container_name: server_nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./workdir:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_php
    networks: 
      - lnmp_network

volumes:
  bdd_mysql_data:

networks:
  lnmp_network:
    driver: bridge