# 

services:

  database:
    image: mariadb:10.11
    container_name: database
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_SCHEMA}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks: 
      - ${CHANGE}_network

  app_php:
    build:
      context: .
      dockerfile: php-dockerfile
    image: php-8.3-fpm-bookworm
    container_name: app_php
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./workdir:/var/www/html
    depends_on:
      - database
    networks: 
      - ${CHANGE}_network
    working_dir: /var/www/html

  web_server:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./workdir:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_php
    networks: 
      - ${CHANGE}_network

volumes:
  database_data:

networks:
  ${CHANGE}_network:
    name: ${CHANGE}_network
    driver: bridge